spring:
  datasource:
#    url: jdbc:mysql://61.136.205.130:3306/canlian?useUnicode=true&characterEncoding=utf-8
#    username: swxcb
#    password: swxcb
    url: jdbc:mysql://10.211.55.9:3306/platform?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  http:
    multipart:
      maxFileSize: 50MB


logging:
  level:
    root: INFO
mybatis:
  mapperLocations: classpath*:mysql/*.xml
